
import { Photograph } from './types';

export const PHOTO_DATA: Photograph[] = [
  {
    id: 1,
    src: "/chruch.jpg",
    alt: "Misty mountains at dawn",
    title: "Mountain Serenity",
    description: "The quiet calm of the mountains as the sun rises, casting a soft glow over the landscape.",
    width: 800,
    height: 1200,
  },
  {
    id: 2,
    src: "https://picsum.photos/seed/b2/1200/800",
    alt: "Bustling city street at night",
    title: "Urban Pulse",
    description: "Neon lights and motion blur capture the vibrant energy of the city after dark.",
    width: 1200,
    height: 800,
  },
  {
    id: 3,
    src: "https://picsum.photos/seed/c3/800/1000",
    alt: "A lone deer in a sunlit forest",
    title: "Forest Guardian",
    description: "A moment of peace as a deer stands bathed in the morning sun rays filtering through the trees.",
    width: 800,
    height: 1000,
  },
  {
    id: 4,
    src: "https://picsum.photos/seed/d4/1200/800",
    alt: "Crashing waves on a rocky shoreline",
    title: "Ocean's Fury",
    description: "The raw power of the ocean is on full display as waves crash against the rugged coast.",
    width: 1200,
    height: 800,
  },
  {
    id: 5,
    src: "https://picsum.photos/seed/e5/800/1200",
    alt: "A close-up of a vibrant flower",
    title: "Nature's Palette",
    description: "Detailed macro shot revealing the intricate textures and colors of a flower in bloom.",
    width: 800,
    height: 1200,
  },
  {
    id: 6,
    src: "https://picsum.photos/seed/f6/1200/800",
    alt: "An old library with towering bookshelves",
    title: "Worlds of Wisdom",
    description: "The scent of old paper and the sight of countless books evoke a sense of timeless knowledge.",
    width: 1200,
    height: 800,
  },
  {
    id: 7,
    src: "https://picsum.photos/seed/g7/800/1000",
    alt: "Portrait of an elderly man with a thoughtful expression",
    title: "A Life's Story",
    description: "Every line on his face tells a story of a life rich with experience and wisdom.",
    width: 800,
    height: 1000,
  },
  {
    id: 8,
    src: "https://picsum.photos/seed/h8/1200/800",
    alt: "Aurora borealis over a frozen lake",
    title: "Celestial Dance",
    description: "The magical northern lights paint the night sky with ethereal green and purple hues.",
    width: 1200,
    height: 800,
  },
  {
    id: 9,
    src: "https://picsum.photos/seed/i9/800/1200",
    alt: "A winding desert road",
    title: "The Journey Ahead",
    description: "An empty road stretching to the horizon, symbolizing endless possibilities and adventure.",
    width: 800,
    height: 1200,
  },
  {
    id: 10,
    src: "https://picsum.photos/seed/j10/1200/900",
    alt: "Minimalist architectural detail",
    title: "Modern Lines",
    description: "Clean lines and geometric shapes create a sense of order and futuristic elegance.",
    width: 1200,
    height: 900,
  },
  {
    id: 11,
    src: "https://picsum.photos/seed/k11/800/1000",
    alt: "A chef meticulously plating a dish",
    title: "Culinary Art",
    description: "The focus and precision of a chef transforming ingredients into a masterpiece.",
    width: 800,
    height: 1000,
  },
  {
    id: 12,
    src: "https://picsum.photos/seed/l12/1200/800",
    alt: "Hot air balloons rising at sunrise",
    title: "Morning Ascent",
    description: "A fleet of hot air balloons peacefully ascends into the golden morning sky.",
    width: 1200,
    height: 800,
  },
];
